import type { Locale } from './locales'

type MethodologyCopy = { title: string; intro: string; sections: { title: string; paragraphs: string[]; items?: string[] }[] }

export const methodologyCopy: Record<Locale, MethodologyCopy> = {
  en: {
    title: 'How SWI evaluates evidence',
    intro: 'Follow a claim back to its source, see the limits of an interpretation, and know when a record needs another review.',
    sections: [
      { title: 'A bounded first collection', paragraphs: ['This release connects four records: ant, stigmergy, ant colony optimization, and artificial-agent coordination through three reviewed relationships. It is an initial research chain, not a complete atlas. The connection from ACO to artificial-agent coordination is labeled editorial synthesis; it does not establish a performance benefit for modern AI agents. No reproducible experiments or measured benchmarks are published in this collection.'] },
      { title: 'The research loop', paragraphs: ['Discover → Collect → Verify → Structure → Connect → Explain → Experiment → Measure → Publish → Revisit.', 'The first six steps govern knowledge records. Experiments and measurements require a defined, reproducible setup. We enter sources first, then evidence records, claims, and entity or relationship references. We verify titles, authors, venue, publication dates, identifiers, links, access dates, and what each source actually establishes. Turkish and English preserve the same scope and limitations.'] },
      { title: 'Source priority', paragraphs: ['Source type and reliability are separate judgments. An official repository may establish implementation behavior without supporting a biological claim. Reporting supplies context and cannot replace primary evidence.'], items: ['Peer-reviewed papers and authoritative scholarly books', 'Original research-group or institutional publications', 'Conference proceedings and standards', 'Official project repositories and technical documentation', 'Reputable technical reporting for context'] },
      { title: 'Claims, evidence, and uncertainty', paragraphs: ['A source is the original publication. An evidence record ties that source to a claim through a locator, a copyright-safe excerpt when useful, and an editorial relevance note. Evidence can support, challenge, or contextualize a claim; contradictions stay visible.', 'Evidence is a bounded statement directly supported by cited material. Synthesis is an editorial interpretation derived from explicit sources. A hypothesis is testable but unestablished. An open question remains unresolved. Confidence is an editorial assessment, not a mathematical probability; contested and not-assessed avoid invented certainty. Missing support is shown as Not established. Biological inspiration does not imply biological identity.'] },
      { title: 'Review and freshness policy', paragraphs: ['Publication date describes the source; access date records retrieval; review date records an evidence check; update date records an edit. An edit or page build does not renew a review.', 'Policy v1: stable foundational biology, mechanisms, and established algorithms use 90 elapsed UTC calendar days; fast-moving AI and project records use 30. The final day is included. A stable record reviewed on 6 September 2026 remains current through 5 December and becomes review-due on 6 December. A fast-moving record with the same review date becomes due on 7 October.', 'Current requires a valid review within its interval and all cited source access states available. A missing or future review date, absent evidence, unavailable or unknown source access, a changed watched dependency, or an explicitly recorded review-due state requires review. Historical and superseded are explicit record overrides; they preserve provenance and do not assert present source availability. The caller supplies the evaluation date; static pages show their evaluation date and refresh on rebuild, not continuously.'] },
      { title: 'AI assistance and publication', paragraphs: ['AI may assist discovery, deduplication, classification, translation, and draft synthesis. A human-reviewable source record remains authoritative. AI output cannot establish bibliographic facts or serve as evidence without independent verification. Unsupported statements are removed or labeled hypotheses or open questions.', 'Publication requires resolving references, valid schemas, evidence for substantive claims, checked source metadata, bilingual scope parity, clear synthesis labels, correct relationship directions, consistent review dates, source-backed timeline dates, and usable desktop and mobile disclosures.'] },
      { title: 'Corrections and maintenance', paragraphs: ['Corrections preserve the earlier public state through a correction note or version history. If a source disappears, its access state changes and an authoritative alternate location may be added while retaining provenance. Changed evidence triggers review of both the claim and its relationships. Superseded material remains attributable.', 'Automated review-candidate discovery is future work; it must not publish unreviewed claims. This release has no public correction-submission form. Corrections currently follow the repository review and version-history process.'] },
    ],
  },
  tr: {
    title: 'SWI kanıtı nasıl değerlendirir?',
    intro: 'Bir iddiayı kaynağına kadar izleyin, yorumun sınırlarını görün ve bir kaydın ne zaman yeniden incelenmesi gerektiğini öğrenin.',
    sections: [
      { title: 'Sınırları belirli ilk koleksiyon', paragraphs: ['Bu sürüm dört kaydı üç incelenmiş ilişkiyle bağlar: karınca, stigmerji, karınca kolonisi optimizasyonu ve yapay ajan koordinasyonu. Bu, kapsamlı bir atlas değil, başlangıç araştırma zinciridir. ACO ile yapay ajan koordinasyonu arasındaki bağlantı editoryal sentez olarak işaretlidir; modern yapay zekâ ajanları için performans artışı kanıtlamaz. Bu koleksiyonda tekrarlanabilir deneyler veya ölçülmüş karşılaştırma sonuçları yayımlanmamıştır.'] },
      { title: 'Araştırma döngüsü', paragraphs: ['Keşfet → Topla → Doğrula → Yapılandır → Bağla → Açıkla → Deney Yap → Ölç → Yayımla → Yeniden İncele.', 'İlk altı adım bilgi kayıtlarını yönetir. Deney ve ölçüm için tanımlı, tekrarlanabilir bir düzenek gerekir. Önce kaynaklar, ardından kanıt kayıtları, iddialar ve varlık ya da ilişki referansları girilir. Başlık, yazar, yayın yeri, yayın tarihi, tanımlayıcı, bağlantı, erişim tarihi ve kaynağın gerçekte neyi gösterdiği doğrulanır. Türkçe ve İngilizce aynı kapsamı ve sınırlamaları korur.'] },
      { title: 'Kaynak önceliği', paragraphs: ['Kaynak türü ile güvenilirlik ayrı değerlendirmelerdir. Resmî bir depo uygulama davranışını gösterebilir; bu, biyolojik bir iddiayı desteklediği anlamına gelmez. Habercilik bağlam sağlar, birincil kanıtın yerini alamaz.'], items: ['Hakemli makaleler ve yetkin akademik kitaplar', 'Özgün araştırma grubu veya kurum yayınları', 'Konferans bildirileri ve standartlar', 'Resmî proje depoları ve teknik belgeler', 'Bağlam için güvenilir teknik habercilik'] },
      { title: 'İddialar, kanıt ve belirsizlik', paragraphs: ['Kaynak, özgün yayındır. Kanıt kaydı; konum bilgisi, yararlı olduğunda telif sınırlarına uygun bir alıntı ve editoryal ilişki notuyla kaynağı iddiaya bağlar. Kanıt bir iddiayı destekleyebilir, sorgulayabilir veya bağlam sağlayabilir; çelişkiler görünür kalır.', 'Kanıt, atıf yapılan içerikle doğrudan desteklenen sınırlı bir ifadedir. Sentez, açık kaynaklardan türetilen editoryal yorumdur. Hipotez test edilebilir ancak henüz doğrulanmamıştır. Açık soru çözümlenmemiştir. Güven düzeyi matematiksel olasılık değil, editoryal değerlendirmedir; tartışmalı ve değerlendirilmedi etiketleri uydurma kesinliği önler. Eksik destek, Kanıtlanmış değil olarak gösterilir. Biyolojik esinlenme, biyolojiyle özdeşlik anlamına gelmez.'] },
      { title: 'İnceleme ve güncellik politikası', paragraphs: ['Yayın tarihi kaynağı, erişim tarihi erişimi, inceleme tarihi kanıt kontrolünü, güncelleme tarihi düzenlemeyi belirtir. Bir düzenleme veya sayfanın yeniden oluşturulması incelemeyi yenilemez.', 'Politika v1: kararlı biyolojik temeller, mekanizmalar ve yerleşik algoritmalar için geçen 90 UTC takvim günü; hızla değişen yapay zekâ ve proje kayıtları için 30 gün uygulanır. Son gün aralığa dahildir. 6 Eylül 2026 tarihinde incelenen kararlı bir kayıt 5 Aralık sonuna kadar güncel kalır, 6 Aralık tarihinde inceleme gerekir. Aynı tarihte incelenen hızlı değişen bir kayıt için 7 Ekim tarihinde inceleme gerekir.', 'Güncel durumu için aralık içinde geçerli bir inceleme ve atıf yapılan tüm kaynakların erişilebilir olması gerekir. Eksik veya gelecekteki inceleme tarihi, kanıt yokluğu, erişilemeyen ya da erişimi bilinmeyen kaynak, izlenen bağımlılık değişikliği veya kayıtlı inceleme gerekir durumu yeniden inceleme gerektirir. Tarihsel ve yerini yenisi aldı açık kayıt tercihleridir; kökeni korur, kaynağın şu an erişilebilir olduğunu ileri sürmez. Değerlendirme tarihi çağıran tarafından sağlanır; statik sayfalar değerlendirme tarihini gösterir ve sürekli değil, yeniden oluşturulduğunda yenilenir.'] },
      { title: 'Yapay zekâ desteği ve yayın', paragraphs: ['Yapay zekâ keşif, yinelenen kayıtları ayıklama, sınıflandırma, çeviri ve sentez taslağına yardımcı olabilir. İnsan tarafından incelenebilir kaynak kaydı belirleyicidir. Yapay zekâ çıktısı bağımsız doğrulama olmadan bibliyografik bilgi veya kanıt olamaz. Desteklenmeyen ifadeler kaldırılır ya da hipotez veya açık soru olarak etiketlenir.', 'Yayın için çözümlenen referanslar, geçerli şemalar, esaslı iddiaların kanıtları, kontrol edilmiş kaynak bilgileri, iki dilde kapsam eşitliği, açık sentez etiketleri, doğru ilişki yönleri, tutarlı inceleme tarihleri, kaynaklı zaman çizelgesi tarihleri ve masaüstü ile mobilde kullanılabilir kanıt açıklamaları gerekir.'] },
      { title: 'Düzeltmeler ve bakım', paragraphs: ['Düzeltmeler, önceki kamusal durumu düzeltme notu veya sürüm geçmişiyle korur. Kaynak kaybolursa erişim durumu değiştirilir; köken korunarak yetkin bir alternatif konum eklenebilir. Değişen kanıt hem iddianın hem ilişkilerinin incelenmesini gerektirir. Yerini yenisi alan içerik kaynağıyla korunur.', 'İnceleme adaylarının otomatik bulunması gelecekteki çalışmadır; incelenmemiş iddiaları yayımlamamalıdır. Bu sürümde herkese açık düzeltme gönderme formu yoktur. Düzeltmeler şu anda depo incelemesi ve sürüm geçmişi sürecini izler.'] },
    ],
  },
}
