import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import AxeBuilder from '@axe-core/playwright'

test.beforeEach(async({page})=>{
  page.on('pageerror',error=>{throw error})
})

test('a biology path produces the configured portable package and an agenda experiment',async({page})=>{
  await page.goto('/tr/atlas/')
  await page.getByRole('searchbox',{name:'Mekanizma veya problem ara'}).fill('arı')
  await page.getByRole('heading',{name:'Bal arıları / Kolektif karar',exact:true}).getByRole('link').click()
  await expect(page.getByRole('heading',{level:1})).toContainText('Bal arıları')
  await page.getByRole('link',{name:'Agent reçetesini aç',exact:true}).click()
  await expect(page).toHaveURL(/\/tr\/recipes\/bees\/$/)
  await page.getByRole('textbox',{name:'Görevin',exact:true}).fill('Verilen üç mimariyi bağımsız kaynaklar ve kabul testleriyle karşılaştır.')
  await page.getByRole('spinbutton',{name:'Agent sayısı',exact:true}).fill('7')
  await page.getByRole('spinbutton',{name:'Tur sınırı',exact:true}).fill('4')
  await page.getByRole('spinbutton',{name:/Toplam token bütçesi/}).fill('14003')
  await page.getByRole('button',{name:'Görev paketini hazırla',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Görev paketin',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'JSON',exact:true}).click()
  const preview=JSON.parse(await page.locator('.wb-code').innerText())
  expect(preview.agents).toHaveLength(7)
  expect(preview.budget).toMatchObject({roundLimit:4,aggregateTokenLimit:14003})
  expect(preview.agents.reduce((sum:number,item:{tokenCap:number})=>sum+item.tokenCap,0)).toBe(14003)
  expect(preview.executionStatus).toBe('not-executed')
  const downloadEvent=page.waitForEvent('download')
  await page.getByRole('button',{name:'JSON indir',exact:true}).click()
  const download=await downloadEvent
  expect(JSON.parse(await readFile((await download.path())!,'utf8'))).toEqual(preview)
  await page.getByRole('button',{name:'Deney planını gündeme ekle',exact:true}).click()
  await page.getByRole('navigation',{name:'Ana gezinme'}).getByRole('link',{name:'Gündemim'}).click()
  const item=page.getByRole('article').filter({hasText:'Arı kovanından karar protokolüne'})
  await expect(item).toBeVisible()
  await item.getByText('Notun tamamını oku',{exact:true}).click()
  await expect(item).toContainText('14003')
  await expect(item.getByRole('combobox')).toHaveValue('experiment')
  await page.reload()
  await expect(item).toBeVisible()
})

test('agenda edits, archive, restore, exports and atomic file imports preserve the record',async({page})=>{
  await page.goto('/en/agenda/')
  await page.getByRole('button',{name:'Add item',exact:true}).click()
  await expect(page.getByRole('textbox',{name:'Title',exact:true})).toBeFocused()
  await page.getByRole('textbox',{name:'Title',exact:true}).fill('My dissent experiment')
  await page.getByRole('textbox',{name:'Source URL (optional)',exact:true}).fill('https://example.org/research')
  await page.getByRole('textbox',{name:'Your note',exact:true}).fill('Keep dissent visible.\n<script>plain text</script>')
  await page.getByRole('combobox',{name:'Related mechanism',exact:true}).selectOption('bees')
  await page.getByRole('button',{name:'Save',exact:true}).click()
  const row=page.getByRole('article').filter({hasText:'My dissent experiment'})
  await expect(row).toContainText('<script>plain text</script>')
  await row.getByRole('button',{name:'Edit',exact:true}).click()
  await page.getByRole('textbox',{name:'Your note',exact:true}).fill('Edited note: keep the counterevidence.')
  await page.getByRole('button',{name:'Save',exact:true}).click()
  await row.getByRole('combobox').selectOption('reading')
  await row.getByRole('button',{name:'Archive',exact:true}).click()
  await expect(row).toHaveCount(0)
  await page.getByRole('button',{name:'Undo',exact:true}).click()
  await expect(row.getByRole('combobox')).toHaveValue('reading')
  const downloadEvent=page.waitForEvent('download')
  await page.getByRole('button',{name:'Export backup',exact:true}).click()
  const backup=await readFile((await(await downloadEvent).path())!,'utf8')
  expect(JSON.parse(backup).entries[0].notes).toBe('Edited note: keep the counterevidence.')
  await page.getByLabel('Import agenda file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(backup)})
  await expect(page.getByRole('status')).toContainText('0 items added; 1 duplicates preserved.')
  const original=await page.evaluate(()=>localStorage.getItem('swi-agenda-v1'))
  await page.getByLabel('Import agenda file').setInputFiles([
    {name:'valid.md',mimeType:'text/markdown',buffer:Buffer.from('# Must not partially import\nAtomic batch')},
    {name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{truncated')},
  ])
  await expect(page.getByRole('main').getByRole('alert')).toContainText('existing agenda is preserved')
  expect(await page.evaluate(()=>localStorage.getItem('swi-agenda-v1'))).toBe(original)
  await page.getByLabel('Import agenda file').setInputFiles({name:'new.md',mimeType:'text/markdown',buffer:Buffer.from('# A new reading\nTürkçe 🐝')})
  await expect(page.getByRole('heading',{name:'A new reading',exact:true})).toBeVisible()
  await page.reload()
  await expect(page.getByRole('article')).toHaveCount(2)
  await expect(row).toContainText('Edited note: keep the counterevidence.')
})

test('research filters, source details and the map remain linked across languages',async({page})=>{
  await page.goto('/tr/')
  await page.getByRole('navigation',{name:'Ana gezinme'}).getByRole('link',{name:'Araştırma',exact:true}).click()
  await expect(page.getByRole('heading',{level:1})).toHaveText('Araştırma kütüphanesi')
  await expect(page.getByRole('navigation',{name:'Dil'}).getByRole('link',{name:'EN',exact:true})).toHaveAttribute('href','/en/research/')
  await page.getByRole('searchbox',{name:'Araştırmalarda ara'}).fill('MAST')
  await expect(page.locator('.wb-study')).toHaveCount(1)
  await page.locator('.wb-study summary').click()
  await expect(page.locator('.wb-study')).toContainText('Özet incelemesi')
  await page.locator('.wb-study').getByRole('button',{name:'Gündeme ekle'}).click()
  await expect(page.locator('.wb-study').getByRole('button')).toBeDisabled()
  await page.getByRole('navigation',{name:'Dil'}).getByRole('link',{name:'EN',exact:true}).click()
  await expect(page).toHaveURL(/\/en\/research\/\?q=MAST$/)
  await expect(page.locator('.wb-study')).toHaveCount(1)
  await page.getByRole('navigation',{name:'Primary navigation'}).getByRole('link',{name:'Knowledge map'}).click()
  await page.getByRole('button',{name:'Honeybees',exact:true}).click()
  await expect(page).toHaveURL(/mechanism=bees/)
  await page.getByRole('link',{name:'Configure this protocol',exact:true}).click()
  await expect(page).toHaveURL(/\/en\/recipes\/bees\/$/)
})

test('core workbench states fit 320px and pass dark-theme accessibility checks',async({page})=>{
  await page.setViewportSize({width:320,height:900})
  for(const route of ['','recipes/bees/','agenda/?new=1','map/']) {
    await page.goto(`/tr/${route}`)
    expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBe(0)
  }
  await page.setViewportSize({width:1440,height:1100})
  await page.goto('/en/recipes/bees/')
  await page.getByRole('button',{name:'Use dark theme',exact:true}).click()
  await expect(page.locator('.action-primary')).toHaveCSS('background-color','rgb(158, 216, 191)')
  const violations=(await new AxeBuilder({page}).analyze()).violations.filter(item=>item.impact==='serious'||item.impact==='critical')
  expect(violations).toEqual([])
})
