import type { Locale } from '@/i18n/locales'
import { localizedPath } from '@/i18n/locales'
import type { Dossier, Study } from '@/research/workbench-schema'
import { MechanismDiagram } from './MechanismDiagram'
import { Icon } from './Icon'
import { PageIntro, TextLink, tx, WorkbenchTopline } from './shared'
import { StudyCard } from './StudyCard'

export function DossierArticle({ dossier, studies, locale }: { dossier: Dossier; studies: Study[]; locale: Locale }) {
  const path = (value: string) => localizedPath(value,locale)
  return <main id="main-content" className="container workbench" tabIndex={-1}><WorkbenchTopline locale={locale} section={tx(locale,'Biyoloji atlası','Biology atlas')} />
    <PageIntro title={`${dossier.name[locale]} / ${dossier.mechanism[locale]}`} description={dossier.question[locale]}><a className="action action-primary" href={path(`/recipes/${dossier.id}/`)}>{tx(locale,'Agent reçetesini aç','Open agent recipe')}<Icon name="arrow" /></a></PageIntro>
    <div className="wb-scientific"><i>{dossier.scientificName}</i> · {dossier.studyIds.length} {tx(locale,'bağlı çalışma','linked studies')} · {tx(locale,'Kaynak kontrolü','Sources checked')}: 06.09.2026</div>
    <div className="wb-article-layout"><article className="wb-article-body">
      <section id="observation"><h2>{tx(locale,'Doğada ne oluyor?','What happens in nature?')}</h2><p>{dossier.observation[locale]}</p><div className="wb-study-links">{studies.filter(study=>study.kind!=='agents').map(study=><a key={study.id} href={`#${study.id}`}>{study.shortTitle} · {study.year}</a>)}</div><div className="wb-note"><strong>{tx(locale,'Aktarımın sınırı','Transfer boundary')}</strong>{dossier.boundary[locale]}</div></section>
      <section id="mechanism"><h2>{tx(locale,'Mekanizmadan protokole','From mechanism to protocol')}</h2><figure className="wb-mechanism-band"><MechanismDiagram topology={dossier.protocol.topology} locale={locale} /><figcaption>{tx(locale,'SWI uyarlaması · kavramsal iletişim şeması','SWI adaptation · conceptual communication diagram')}</figcaption></figure><table className="wb-mapping"><thead><tr><th>{tx(locale,'Biyolojide','In biology')}</th><th>{tx(locale,'Agent süründe deneyebileceğin karşılık','A counterpart to test in your agents')}</th></tr></thead><tbody>{dossier.mappings.map((mapping,index)=><tr key={index}><td>{mapping.nature[locale]}</td><td>{mapping.agent[locale]}</td></tr>)}</tbody></table></section>
      <section id="application"><h2>{tx(locale,'Kendi süründe nasıl kullanırsın?','How can you use it in your swarm?')}</h2><p>{dossier.protocol.purpose[locale]}</p><ol className="wb-step-list">{dossier.protocol.steps.map((step,index)=><li key={index}><span className="wb-step-number" aria-hidden="true">0{index+1}</span><div><h3>{step.title[locale]}</h3><p>{step.body[locale]}</p></div></li>)}</ol><TextLink href={path(`/recipes/${dossier.id}/`)}>{tx(locale,'Görev, agent sayısı ve bütçeyle reçeteyi hazırla','Configure the recipe with your task, agent count and budget')}</TextLink></section>
      <section id="experiment"><h2>{tx(locale,'Bir deneyle başla','Start with an experiment')}</h2><p>{dossier.protocol.experiment[locale]}</p><dl className="wb-definition-list"><dt>{tx(locale,'Mekanizmayı kaldırdığında ne olur?','What happens if you remove the mechanism?')}</dt><dd>{dossier.protocol.ablation[locale]}</dd><dt>{tx(locale,'Başlıca hata riski','Primary failure risk')}</dt><dd>{dossier.protocol.failure[locale]}</dd></dl></section>
      <section id="sources"><h2>{tx(locale,'Dayanaklar ve ilgili çalışmalar','Evidence and related studies')}</h2><p>{tx(locale,'Biyolojik dayanak ile agent araştırmasını ayrı oku. Aşağıdaki mühendislik yorumları SWI sentezidir.','Read biological evidence and agent research separately. The engineering interpretations below are SWI synthesis.')}</p>{studies.map(study=><StudyCard key={study.id} study={study} locale={locale} headingLevel={3} />)}</section>
    </article><aside className="wb-reading-rail"><h2>{tx(locale,'Bu dosyada','In this dossier')}</h2><nav className="wb-toc" aria-label={tx(locale,'Dosya bölümleri','Dossier sections')}>{[['observation',tx(locale,'Biyolojik gözlem','Biological observation')],['mechanism',tx(locale,'Aktarım haritası','Transfer map')],['application',tx(locale,'Agent uygulaması','Agent application')],['experiment',tx(locale,'Deney fikri','Experiment idea')],['sources',tx(locale,'Çalışmalar ve kaynaklar','Studies and sources')]].map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav><div className="wb-note"><strong>{tx(locale,'İlk denemede','For your first trial')}</strong>{tx(locale,'Tek agent kontrolünü koru. Aynı görev, aynı kabul ölçütü, aynı toplam bütçeyi kullan.','Keep a single-agent control. Use the same task, acceptance criteria and aggregate budget.')}</div><TextLink href={path('/atlas/')}>{tx(locale,'Tüm biyoloji dosyaları','All biology dossiers')}</TextLink></aside></div>
  </main>
}
